# Generated by Django 4.2.2 on 2023-06-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0002_forfait'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forfait_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customModels.forfait'),
        ),
    ]
