# Generated by Django 4.2.2 on 2023-06-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0003_customuser_forfait_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='forfait_id',
            new_name='forfait',
        ),
    ]
