# Generated by Django 4.2.2 on 2023-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0004_rename_forfait_id_customuser_forfait'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
