# Generated by Django 4.2.3 on 2023-07-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0007_states_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
