# Generated by Django 4.2.3 on 2023-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0008_rename_class_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='folderName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
