# Generated by Django 4.2.3 on 2023-09-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0010_remove_customuser_forfait_customuser_jetons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(max_length=255)),
                ('sequence', models.CharField(max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customModels.project')),
            ],
        ),
    ]
