# Generated by Django 4.2.3 on 2023-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0013_feedbacklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklog',
            name='feedback',
            field=models.TextField(max_length=2500),
        ),
    ]
